### ISSUE TITLE
Help with single library with one replicate 

### ISSUE THREAD

**Issue by Biomaagi** [immunogenomics/SCENT#2]
Hi,

How would one run SCENT in a situation that has only one sample and batch available? 
As of now, I have tried to omit these two covariates from the SCENT model, but this seems to cause some peculiar outputs with the bootstrap p-value being significantly poorer compared to the one from Poisson regression. Additionally, the bootstrap p-values seem to come out in sequences, where the same p-val is repeated for hundreds or thousands of gene-peak pairs. Is this the expected behaviour? From what I gather, wouldn't you expect only the lowest p-value to repeat when the calculation hits its cap?

Thank you in advance!

**Comment by saorisakaue** [comment]
Hello,

Apologies for super delayed response. I don't think it is because of your dataset comprising of one sample and one batch, but it could probably because the number of cells from your dataset is smaller than what we think is appropriate. If your data is small and less powered, it could be possible that boot p values have sequences of same values due to limited numbers of bootstrapping for less significant associations. From our experiences, the model would perform relatively poorly especially when the number of cells < 2000 in the cell type your are investigating.
I hope this helps!

Thanks,
Saori
